### ISSUE TITLE
Make host & port of tweeboparser and corenlp configurable

### ISSUE THREAD

**Issue by kanihal** [apmoore1/Bella#4]
Hi,
Thanks for starting this project, much needed and very useful.

Could you please make host & port of tweeboparser and corenlp configurable?

I had too many containers running and 9000 was already being used, so I had to change port in _stanford_tools.py_.  Since _pip install_ is being used for module installation, it would be better to provide configurable options so as to avoid need for changing source code. 
Also, you might want to choose a different default port other than 9000, Since **portainer**  which many people use for managing containers also like corenlp uses 9000 as it's default port.

**Comment by apmoore1** [comment]
Hi,

Sorry for the delay in replying to this.

Thanks, I'm glad you have found it useful.

Yes I will get around to fixing this issue tomorrow.

**Comment by apmoore1** [comment]
Sorry I didn't mean to close this. If you read under the subsection [Docker Servers](https://github.com/apmoore1/Bella#docker-servers) in the new README this should explain how this issue has been fixed. I have also created a new release which can be installed via pip:
`pip install -U bella-tdsa`
which is up to date with this fix.

**Comment by kanihal** [comment]
Thanks for the fix.
